name: finote-app

services:
  server:
    container_name: finote-server
    image: finote-server:latest
    build:
      context: ../server
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    logging:
      driver: 'json-file'
    ports:
      - '30010:3000'
    networks:
      net:
    environment:
      NODE_ENV: ${NODE_ENV}
      TZ: ${TZ}
      PORT: ${PORT}
      DEBUG: ${DEBUG}
      COOKIE_SECRET: ${COOKIE_SECRET}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_SSL: ${DATABASE_SSL}
      SENTRY_DSN: ${SENTRY_DSN}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

networks:
  net:
    name: net
